[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#types#git#clone_depth=1
'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

# telescope
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
source ~/.vim/telescope.rc.vim
'''

# neosnippet
[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# appearance
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_source = '''
lua << EOF
require("indent_blankline").setup {
  show_end_of_line = true,
}
EOF
'''

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'lua require("config/lualine")'

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = 'lua require("bufferline").setup{}'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
let g:better_whitespace_enabled=1
let g:better_whitespace_filetypes_blacklist = ['defx', 'markdown', 'gitcommit']
let g:better_whitespace_operator=''
augroup MyIndentGuides
  autocmd!
  autocmd FileType help DisableWhitespace
augroup END
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
lua require('config/treesitter')
'''

[[plugins]]
repo = 'RRethy/nvim-treesitter-textsubjects'

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'

# edit
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
runtime macros/sandwich/keymap/surround.vim
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'JoosepAlviste/nvim-ts-context-commentstring'
merged = 0

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
map ; <Plug>(clever-f-repeat-forward)
map , <Plug>(clever-f-repeat-back)
let g:clever_f_use_migemo = 1
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'

# lexima
[[plugins]]
repo = 'cohama/lexima.vim'
hook_post_source = 'source ~/.vim/lexima.rc.vim'

[[plugins]]
repo = "sbdchd/vim-shebang"
hook_add = '''
let g:shebang#shebangs = {
      \ 'sh': '#!/bin/bash',
      \ }
'''

[[plugins]]
repo = 'justinmk/vim-sneak'
hook_add = '''
let g:sneak#label = 1
'''

# textobj
[[plugins]]
repo = 'michaeljsmith/vim-indent-object'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'tpope/vim-repeat'

# git
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = "lua require('gitsigns').setup()"

# Japanese
[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'deton/jasegment.vim'

# filetype
[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'sophacles/vim-processing'

# terminal
[[plugins]]
repo = 'voldikss/vim-floaterm'
hook_add = '''
" tnoremap <C-]> <C-\><C-n>
let g:floaterm_keymap_toggle = '<C-g>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9

" use like quickrun
augroup MyNeoterm
  autocmd!
  autocmd FileType rust nnoremap <Leader>r :FloatermNew cargo run<CR>
  autocmd FileType rust nnoremap <Leader>R :FloatermSend cargo run<CR>:FloatermToggle<CR>
  autocmd FileType rust nnoremap <Leader>t :FloatermNew cargo test<CR>
  autocmd FileType rust nnoremap <Leader>T :FloatermSend cargo test<CR>:FloatermToggle<CR>
augroup END
'''

# colorscheme
[[plugins]]
repo = 'sainnhe/edge'
