[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 )"
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neocomplcache'
if = "!(has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 ))"
on_event = 'InsertEnter'
