[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 )"
on_event = 'InsertEnter'
depends = 'neco-look'

[[plugins]]
repo = 'Shougo/neocomplcache'
if = "!(has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 ))"
on_event = 'InsertEnter'

[[plugins]]
repo = 'ujihisa/neco-look'
if = "executable('look')"

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = 'source ~/.vim/lexima.rc.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'matze/vim-lilypond'
on_ft = 'lilypond'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
hook_add = '''
augroup MyAutoCmd
  autocmd BufRead,BufNewFile *.toml setfiletype toml
augroup END
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NerdTree', 'NerdTreeToggle']
hook_add = '''
nnoremap <silent> <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertEnter'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['ruby', 'python']

[[plugins]]
repo = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
hook_add = '''
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)
" clear status
nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

# colorscheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'jacoborus/tender'
