[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
hook_add = '''
lua << EOF
require'nvim_lsp'.rust_analyzer.setup{}

-- define wrapper function for formatting
-- to avoid cursor moving to first line
function formatting_retain_line()
  local line_number = vim.api.nvim_eval("line('.')")
  vim.lsp.buf.formatting_sync()
  vim.api.nvim_command('normal ' .. line_number .. 'G')
end
EOF

" The prefix key.
nnoremap [lsp] <Nop>
nmap     <Space>l      [lsp]

nnoremap [lsp]l <cmd>Commands<CR>^Lsp !Install<Space>
nnoremap [lsp]d <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap [lsp]h <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap [lsp]r <cmd>lua vim.lsp.buf.rename()<CR>
nnoremap [lsp]a <cmd>lua vim.lsp.buf.code_action()<CR>
nnoremap [lsp]f <cmd>lua formatting_retain_line()<CR>
nnoremap [lsp]T <cmd>lua require'lsp_extensions'.inlay_hints()<CR>
nnoremap [lsp]t <cmd>lua require'lsp_extensions'.inlay_hints{ only_current_line = true }<CR>

" Define lsp commands
" Use costum function for "formatting"
command LspFormatting :lua formatting_retain_line()<CR>
lua << EOF
function define_lsp_command(cmd, fun)
  local def_cmd = 'command Lsp' .. cmd .. ' :lua vim.lsp.buf.' .. fun .. '()<CR>'
  vim.api.nvim_command(def_cmd)
end

-- Define command except for "formatting"
define_lsp_command('ClearReference', 'clear_reference')
define_lsp_command('CodeAction', 'code_action')
define_lsp_command('Declaration', 'declaration')
define_lsp_command('Definition', 'definition')
define_lsp_command('DocumentHighlight', 'document_highLight')
define_lsp_command('DocumentSynbol', 'document_synbol')
define_lsp_command('Hover', 'hover')
define_lsp_command('Inplementation', 'inplementation')
define_lsp_command('IncomingCalls', 'incoming_calls')
define_lsp_command('OutgoingCalls', 'outgoing_calls')
define_lsp_command('References', 'references')
define_lsp_command('Rename', 'rename')
define_lsp_command('SignatureHelp', 'signature_help')
define_lsp_command('TypeDefinition', 'type_definition')
define_lsp_command('WorkspaceSymbol', 'workspace_symbol')
EOF

highlight link LspDiagnosticsError ErrorMsg
highlight link LspDiagnosticsVirtualTextError ErrorMsg
highlight link LspDiagnosticsDefaultError ErrorMsg
highlight link LspDiagnosticsWarning Comment
highlight link LspDiagnosticsVirtualTextWarning Comment
highlight link LspDiagnosticsDefaultWarning Comment
highlight link LspDiagnosticsInformation Comment
highlight link LspDiagnosticsVirtualTextInformation Comment
highlight link LspDiagnosticsDefaultInformation Comment
highlight link LspDiagnosticsHint Comment
highlight link LspDiagnosticsVirtualTextHint Comment
highlight link LspDiagnosticsDefaultHint Comment

lua << EOF
vim.lsp.handlers["textDocument/rename"] = function(_err, _method, result)
    if not result then return end
    if result.documentChanges then
        local merged_changes = {}
        local versions = {}
        for _, change in ipairs(result.documentChanges) do
            if change.kind then
                error("not support")
            else
                local edits = merged_changes[change.textDocument.uri] or {}
                versions[change.textDocument.uri] = change.textDocument.version
                for _, edit in ipairs(change.edits) do
                    table.insert(edits, edit)
                end
                merged_changes[change.textDocument.uri] = edits
            end
        end
        local new_changes = {}
        for uri, edits in pairs(merged_changes) do
            table.insert(new_changes, {
                edits = edits,
                textDocument = {
                    uri = uri,
                    version = versions[uri],
                }})
        end
        result.documentChanges = new_changes
    end

    vim.lsp.util.apply_workspace_edit(result)
end
EOF
'''

[[plugins]]
repo = 'RishabhRD/popfix'

[[plugins]]
repo = 'RishabhRD/nvim-lsputils'
hook_add = '''
lua <<EOF
vim.lsp.handlers['textDocument/codeAction'] = require'lsputil.codeAction'.code_action_handler
vim.lsp.handlers['textDocument/references'] = require'lsputil.locations'.references_handler
vim.lsp.handlers['textDocument/definition'] = require'lsputil.locations'.definition_handler
vim.lsp.handlers['textDocument/declaration'] = require'lsputil.locations'.declaration_handler
vim.lsp.handlers['textDocument/typeDefinition'] = require'lsputil.locations'.typeDefinition_handler
vim.lsp.handlers['textDocument/implementation'] = require'lsputil.locations'.implementation_handler
vim.lsp.handlers['textDocument/documentSymbol'] = require'lsputil.symbols'.document_handler
vim.lsp.handlers['workspace/symbol'] = require'lsputil.symbols'.workspace_handler
EOF
'''

[[plugins]]
repo = 'nvim-lua/lsp_extensions.nvim'
