[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
hook_source = '''
lua require('config/nvim_cmp')
'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'
