[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'Shougo/deoplete-lsp'
hook_add = '''
lua << EOF
require'nvim_lsp'.rust_analyzer.setup{}
EOF

" The prefix key.
nnoremap [lsp] <Nop>
nmap     <Space>l      [lsp]

nnoremap [lsp]l :call LanguageClient_contextMenu()<CR>
nnoremap [lsp]d <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap [lsp]h <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap [lsp]r <cmd>lua vim.lsp.buf.rename()<CR>
nnoremap [lsp]a <cmd>lua vim.lsp.buf.code_action()<CR>
nnoremap [lsp]f <cmd>lua vim.lsp.buf.formatting()<CR>
'''

[[plugins]]
repo = 'RishabhRD/popfix'

[[plugins]]
repo = 'RishabhRD/nvim-lsputils'
hook_add = '''
lua <<EOF
vim.lsp.handlers['textDocument/codeAction'] = require'lsputil.codeAction'.code_action_handler
vim.lsp.handlers['textDocument/references'] = require'lsputil.locations'.references_handler
vim.lsp.handlers['textDocument/definition'] = require'lsputil.locations'.definition_handler
vim.lsp.handlers['textDocument/declaration'] = require'lsputil.locations'.declaration_handler
vim.lsp.handlers['textDocument/typeDefinition'] = require'lsputil.locations'.typeDefinition_handler
vim.lsp.handlers['textDocument/implementation'] = require'lsputil.locations'.implementation_handler
vim.lsp.handlers['textDocument/documentSymbol'] = require'lsputil.symbols'.document_handler
vim.lsp.handlers['workspace/symbol'] = require'lsputil.symbols'.workspace_handler
EOF
'''
