[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 )"
on_event = 'InsertEnter'
depends = 'neco-look'

[[plugins]]
repo = 'Shougo/neocomplcache'
if = "!(has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 ))"
on_event = 'InsertEnter'

[[plugins]]
repo = 'ujihisa/neco-look'
if = "executable('look')"

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertCharPre'
hook_post_source = 'source ~/.vim/lexima.rc.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'matze/vim-lilypond'
on_ft = 'lilypond'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NerdTree', 'NerdTreeToggle']

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['ruby', 'python']

[[plugins]]
repo = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'
