[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#types#git#clone_depth=1
'''

[[plugins]]
repo = 'haya14busa/dein-command.vim'

# denite
[[plugins]]
repo = 'chemzqm/unite-location'

[[plugins]]
repo = "kmnk/denite-dirmark"

# appearance
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
augroup MyIndentGuides
  autocmd!
  autocmd FileType defx IndentGuidesDisable
  autocmd FileType neoterm IndentGuidesDisable
augroup END
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/lightline.rc.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
let g:better_whitespace_enabled=1
let g:better_whitespace_filetypes_blacklist = ['defx', 'markdown']
let g:better_whitespace_operator=''
augroup MyIndentGuides
  autocmd!
  autocmd FileType help DisableWhitespace
augroup END
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

# edit
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = "sbdchd/vim-shebang"
hook_add = '''
let g:shebang#shebangs = {
      \ 'sh': '#!/bin/bash',
      \ }
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_lint_on_text_changed = 0
let g:ale_linters = {'ruby': ['ruby', 'rubocop']}
let g:ale_disable_lsp = 1
if !has('gui_macvim')
  let g:ale_sign_error = '⨉'
  let g:ale_sign_warning = '⚠'
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '']
else
  let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', '']
endif
'''

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_map_keys = 0
'''

# Japanese
[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'deton/jasegment.vim'

# filetype
[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['tex']
'''
