[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_post_source = 'source ~/.vim/lexima.rc.vim'

# filetype pluins

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
hook_add = '''
augroup MyAutoCmd
  autocmd BufRead,BufNewFile *.toml setfiletype toml
augroup END
'''

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = 'html'

# filetype pluins ここまで

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NerdTree', 'NerdTreeToggle']
hook_add = '''
nnoremap <silent> <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertEnter'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'rhysd/committia.vim'
on_path = 'COMMIT_EDITMSG'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
on_map = '<Plug>'
hook_add = '''
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star-with-echo)
nmap # <Plug>(anzu-sharp-with-echo)
" clear status
nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
hook_add = '''
" カーソル移動時の自動切り替えを無効化
let g:precious_enable_switch_CursorMoved = {
      \	"*" : 0
      \}
let g:precious_enable_switch_CursorMoved_i = {
      \	"*" : 0
      \}

" insert に入った時にスイッチし、抜けた時に元に戻す
augroup test
  autocmd!
  autocmd InsertEnter * :PreciousSwitch
  autocmd InsertLeave * :PreciousReset
augroup END
'''

[[plugins]]
repo = 'Shougo/unite-outline'

# colorscheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'
