[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'
depends = 'Shougo/dein.vim'

# UI
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = 'Shougo/unite.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'easymotion/vim-easymotion'

# colorscheme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# edit
[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# language
[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'matze/vim-lilypond'

[[plugins]]
repo = 'cespare/vim-toml'

# Japanese
[[plugins]]
repo = 'haya14busa/vim-migemo'

[[plugins]]
repo = 'deton/jasegment.vim'

# others
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'
