[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim') && has('python3')"
on_event = 'InsertEnter'
depends = 'neco-look'
hook_add = '''
" Use deoplete.
let g:deoplete#enable_at_startup = 1
" Use smartcase.
let g:deoplete#enable_smart_case = 1

" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function() abort
  return deoplete#close_popup() . "\<CR>"
endfunction
'''
hook_post_source = '''
call deoplete#custom#source('look', 'rank', 50)
call deoplete#custom#source('tabnine', 'rank', 80)
'''

[[plugins]]
repo = 'ujihisa/neco-look'
if = "executable('look')"

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'wellle/tmux-complete.vim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'ncm2/float-preview.nvim'
hook_add = '''
set completeopt-=preview
function! s:set_preview_docked()
  if winwidth('%') > 80
    let g:float_preview#docked = 0
  else
    let g:float_preview#docked = 1
  endif
endfunction
call s:set_preview_docked()
augroup MyFloadPreview
  autocmd!
  autocmd VimResized * call s:set_preview_docked()
augroup END
'''
