[[plugins]]
repo = 'Shougo/neocomplete'
if = "has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 )"
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neocomplcache'
if = "!(has('lua') && ( (v:version == 703 && has('patch885')) || v:version >= 704 ))"
on_event = 'InsertEnter'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertCharPre'
hook_post_source = 'source ~/.vim/lexima.rc.vim'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NerdTree', 'NerdTreeToggle']

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<Plug>'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'Gstatus', 'Gdiff']

[[plugins]]
repo = 'Shougo/neosnippet'
depends = 'neosnippet-snippets'
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

